apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: b4bz/homer
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /www/assets
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homer-config
---
apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  type: NodePort
  selector:
    app: homer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer
spec:
  ingressClassName: nginx
  rules:
    - host: homer.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homer
                port:
                  number: 80
